debug: true

server:
  port: 8087
  max-http-request-header-size: 8KB
  shutdown: graceful  # 支持优雅停止服务（Ctrl+C，kill -15 <pid>）
  servlet:
    context-path: /           # ij-boot
    application-display-name: ij-boot

spring:
  main:
    web-application-type: servlet
  application:
    name: ij-boot
    admin:
      enabled: true
      jmx-name: org.springframework.boot:type=Admin,name=SpringApplication
  # 运行环境：dev-开发环境、sit-集成测试、prod-生成环境
  profiles:
    active: dev
    include: core
