debug: true

server:
  port: 8088
  max-http-header-size: 8KB
  shutdown: graceful  # 支持优雅停止服务（kill -2 <pid>）
  servlet:
    context-path: /           # ij-boot
    application-display-name: ijleex-boot

spring:
  application:
    name: ijleex-boot
    admin:
      enabled: true
      jmx-name: org.springframework.boot:type=Admin,name=SpringApplication
  # 运行环境：dev-开发环境、sit-集成测试、prod-生成环境
  profiles:
    #active: dev
    include: core
