spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: *
    port: 6379
    timeout: 30s
    client-type: lettuce
    cluster:
      nodes: 127.0.0.1:6379
      max-redirects: 6
    lettuce:
      pool:
        min-idle: 0
        max-idle: 10
        max-active: 100
        max-wait: 30s
        time-between-eviction-runs: 30s
