debug: true

server:
  port: 8080
  servlet:
    application-display-name: ijleex-boot
    context-path: /           # ij-boot

spring:
  application:
    name: ijleex-boot
    admin:
      enabled: true
      jmx-name: org.springframework.boot:type=Admin,name=SpringApplication
  # 运行环境：dev-开发环境、sit-集成测试、prod-生成环境
  profiles:
    #active: dev
    include: core
