spring:
  data:
    redis:
      database: 0
      host: 127.0.0.1
      username: default
      password: 123456
      port: 6379
      timeout: 120s
      connect-timeout: 60s
      client-type: lettuce
      cluster:
        nodes: 127.0.0.1:6379
        max-redirects: 6
      ssl:
        enabled: false
      lettuce:
        pool:
          enabled: true
          max-idle: 10
          min-idle: 0
          max-active: 100
          max-wait: 30s
          time-between-eviction-runs: 30s
