--
-- 输入法词条 PostgreSQL 处理
--

DROP DATABASE IF EXISTS db_ime_dict;
CREATE DATABASE db_ime_dict
  WITH
  OWNER = devel
  TEMPLATE = "template1"
  ENCODING = 'UTF8'
  LC_COLLATE = 'en_US.utf8'
  LC_CTYPE = 'en_US.utf8'
  TABLESPACE = "pg_default"
  CONNECTION LIMIT -1;


-- 输入法词库
DROP TABLE IF EXISTS t_ime_dict;
-- TRUNCATE TABLE t_ime_dict;
CREATE TABLE t_ime_dict (
  id     INTEGER generated by default as identity,
  text   VARCHAR(200) NOT NULL,
  code   VARCHAR(5)   NOT NULL,
  weight INTEGER      NOT NULL DEFAULT 0,
  stem   VARCHAR(4),
  type   VARCHAR(10)  NOT NULL DEFAULT '-',
  CONSTRAINT pk_ime_dict PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_ime_dict ON t_ime_dict (text, code);

COMMENT ON TABLE t_ime_dict IS '输入法词库';
COMMENT ON COLUMN t_ime_dict.id IS 'ID';
COMMENT ON COLUMN t_ime_dict.text IS '词条';
COMMENT ON COLUMN t_ime_dict.code IS '编码';
COMMENT ON COLUMN t_ime_dict.weight IS '词频，用于排序（数字越大候选列表位置越靠前）';
COMMENT ON COLUMN t_ime_dict.stem IS '构词码（形码输入法）';
COMMENT ON COLUMN t_ime_dict.type IS '词条类型';


/*
 * Copyright 2011-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0.
 * See `LICENSE` in the project root for license information.
 */


-- ----------------------------------------------------------
-- 统计每个编码的词条数（数据好多，不要在命令行中执行）
SELECT COUNT(*)
FROM t_ime_dict
GROUP BY code INTO OUTFILE 'D:/ProgramFiles/MySQL/mysql-8.0.22-winx64/docs/count-out.txt'
  FIELDS TERMINATED BY '\t' ENCLOSED BY '' ESCAPED BY '\\'
  LINES STARTING BY '' TERMINATED BY '\n';

SELECT code, COUNT(*) AS count0
FROM t_ime_dict
GROUP BY code
HAVING COUNT(*) > 400;
-- -----------------------------------------------------------

-- 统计每个字母的编码、词条总数（MySQL SUBSTR(str,pos,len) pos从1开始的）
SELECT SUBSTR(code, 1, 1) AS letter,
       COUNT(*)           AS count
FROM t_ime_dict
GROUP BY letter
ORDER BY letter
INTO OUTFILE 'D:/ProgramFiles/MySQL/mysql-8.0.22-winx64/docs/dict-out.txt'
  FIELDS TERMINATED BY '\t' ENCLOSED BY '' ESCAPED BY '\\'
  LINES STARTING BY '' TERMINATED BY '\n';

-- 按字母、类型统计词条数 2018-05-02 17:58:22
SELECT SUBSTR(code, 1, 1) AS       letter,
       COUNT(text)        AS       词条数,
       SUM(IF(type = '-', 1, 0))   常用字,
       SUM(IF(type = '类1', 1, 0)) 词组,
       SUM(IF(type = '类2', 1, 0)) 快捷符号,
       SUM(IF(type = '类3', 1, 0)) 命令直通车,
       SUM(IF(type = '次', 1, 0))  生僻字,
       SUM(IF(type = '用', 1, 0))  用户词,
       SUM(IF(type = '辅', 1, 0))  辅码
FROM t_ime_dict
GROUP BY letter
ORDER BY letter;
